#! /bin/bash


########################
####   AUTO START   ####

# --- comands ---
xset r rate 170 40 &
setxkbmap -layout us,ru -option grp:alt_shift_toggle &
xsetroot -cursor_name left_ptr &

# --- apps ---
sxhkd &
polybar example &
nitrogen --restore &
#firefox &
#xfce4-terminal &

####   AUTO START   ####
########################



#############################
####   FRAMEs AND GAPS   ####

bspc config border_width         1
bspc config window_gap           5

# --- gaps only between windows ---
bspc config window_gap $gap;
bspc config top_padding -$(($gap+2))
bspc config left_padding -$(($gap+2))
bspc config right_padding -$(($gap+4))
bspc config bottom_padding $(($PANEL_HEIGHT-$gap))

# --- disabling gaps with one window ---
bspc config borderless_monocle   false 
bspc config gapless_monocle      false
bspc config paddingless_monocle	 true

# --- full screen mode with one window ---
bspc config single_monocle	     false

####   FRAMEs AND GAPS   ####
#############################



##############################
####   COLOR OF WINDOWs   ####

#--- frames in different states ---
#bspc config normal_border_color "#23252e"
#bspc config active_border_color "#23252e"
bspc config focused_border_color "#707070"

# --- space color when selecting location of new window ---
bspc config presel_feedback_color "fd2e59"

####   COLOR OF WINDOWs   ####
##############################



#########################################
####   WINDOW FOCUS ON MOUSE HOVER   ####

bspc config focus_follows_pointer true
bspc config pointer_modifier	super

####   WINDOW FOCUS ON MOUSE HOVER   ####
#########################################



#############################
####   WINDOW BEHAVIOR   ####

#bspc rule -a firefox state=floating follow=off rectangle=1350x900+50+90 desktop='^2'
#bspc rule -a TelegramDesktop state=floating follow=off desktop='^1'
#bspc rule -a TelegramDesktop state=floating follow=off rectangle=420x900+1450+90 desktop='^1'
#bspc rule -a Steam state=floating follow=off rectangle=1350x900+285+90 desktop='^6' 
#bspc rule -a mpv state=floating rectangle=800x450+560+315 follow=off
#bspc rule -a dmenu rectangle=900x22+610+90
#bspc rule -a Media viewer rectangle=1350x900+285+90 state=floating
#bspc rule -a Inkscape desktop='^3'
#bspc rule -a Blender desktop='^2'

####   WINDOW BEHAVIOR   ####
#############################



########################
####   WORKSPACEs   ####

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

####   WORKSPACEs   ####
########################



####################################
####   WINDOW OPENING SCHEMES   ####

# --- coefficient separation ---
bspc config split_ratio          0.5

# --- window division type ---
#bspc config automatic_scheme	spiral

####   WINDOW OPENING SCHEMES   ####
####################################
